version: '3.9'
services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'

  api:
    build: ../apps/api-simple
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
      - MONGO_URI=mongodb://mongo:27017/task-boards
    depends_on:
      - mongo

  web:
    build:
      context: ../apps/web-simple
      args:
        - VITE_API_URL=http://localhost:4000/api
    ports:
      - '5173:5173'
    depends_on:
      - api
